image: python:latest
    
stages:
  - test

test:
  stage: test
  script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-numpy python3-scipy python3-pytest
  - PYTHONPATH=lib pytest-3
