image: debian:buster-slim

stages:
  - test

test:
  stage: test
  script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-numpy python3-scipy python3-pytest python3-sklearn
  - PYTHONPATH=lib pytest-3
